databaseChangeLog:
  - changeSet:
      id: 005-add-user-id-to-job-applications
      author: Jeff Gladstone
      changes:
        - addColumn:
            tableName: job_applications
            columns:
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: true

        - addForeignKeyConstraint:
            baseTableName: job_applications
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            constraintName: fk_job_applications_user
