spring:
  sql:
    init:
      mode: never
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    type: simple  # (default) uses ConcurrentHashMap

info:
  app:
    name: Job Application Tracker
    description: A full-stack app
    version: 1.0.0
cors:
  allowed-origins: http://localhost:3000
logging:
  level:
    org.springframework.security: DEBUG
    web: DEBUG
    root: INFO