spring:
  sql:
    init:
      mode: never
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
info:
  app:
    name: Job Application Tracker
    description: A full-stack app
    version: 1.0.0
